apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: openclaw-secrets
  namespace: openclaw
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: openclaw-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "openclaw-k3s-oracle-arm-credentials"
