version: 2
updates:
  - package-ecosystem: docker
    directories:
      - "/on-premise/*"
      - "/oracle-arm/*"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker

  - package-ecosystem: terraform
    directories:
      - "/terraform/*"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - terraform
