apiVersion: vault.oci.upbound.io/v1alpha1
kind: Secret
metadata:
  name: db-heatwave-user-wordpress-sologemma-password
  annotations:
    crossplane.io/external-name: "ocid1.vaultsecret.oc1.eu-milan-1.amaaaaaabq3tbnaagitucwz2oasncflgqxbediup7buqu5afkg3nwmkadr2q"
spec:
  managementPolicies: ["Observe"]
  forProvider:
    compartmentId: "ocid1.tenancy.oc1..aaaaaaaaic5nx2ifziikvx56su334ruzxqlmujowvwpfy7jodzvomlskbf2q"
    secretName: db-heatwave-user-wordpress_sologemma-password
    vaultId: "ocid1.vault.oc1.eu-milan-1.hjuzrsdpaae3g.abwgsljr4femfu6eqjtogsw3hr7lkjve27ymrtlhsfzv3ms5rkm3u3yyaj5a"
    keyId: "ocid1.key.oc1.eu-milan-1.hjuzrsdpaae3g.abwgsljrocgwohzkinylkgbbxgyiuzgugkxlsu566xdrv56zsq64ldtjxl7a"
  providerConfigRef:
    name: default
