apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel-ingress-controller
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: cloudflare-tunnel-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "cloudflare-tunnel-k3s-oracle-arm-credentials"
