apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      vault: "ocid1.vault.oc1.eu-milan-1.hjuzrsdpaae3g.abwgsljr4femfu6eqjtogsw3hr7lkjve27ymrtlhsfzv3ms5rkm3u3yyaj5a"
      region: eu-milan-1
      principalType: InstancePrincipal
