apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: operator-oauth
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: "tailscale-k3s-oracle-arm-oauth-credentials"
