version: "3"
services:
    cloudflared:
      image: cloudflare/cloudflared:latest
      container_name: cloudflare-tunnel
      command: tunnel run
      restart: always
      environment:
        NO_AUTOUPDATE: true
        TUNNEL_TOKEN: ${TUNNEL_TOKEN}