apiVersion: oci.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  region: eu-milan-1
  credentials:
    source: InjectedIdentity
