apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-family-oci
spec:
  package: xpkg.upbound.io/upbound/provider-family-oci:v0.1.3
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: upbound-provider-oci-kms
spec:
  package: xpkg.upbound.io/upbound/provider-oci-kms:v0.1.3
