version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - ${HOST_IP}:53:53/udp
      - 67:67/udp
      - ${PIHOLE_UI_HOST_PORT}:80/tcp
      - ${PIHOLE_HTTPS_PORT}:443/tcp
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DNSMASQ_USER=${DNSMASQ_USER}
      - PIHOLE_UID=${PIHOLE_UID}
    volumes:
       - '${DOCKER_VOL_ROOT_DIR}/pihole_etc:/etc/pihole/'
       - '${DOCKER_VOL_ROOT_DIR}/pihole_etc-dnsmasq.d:/etc/dnsmasq.d/'
    dns:
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: always
    networks:
      pihole:
        ipv4_address: "${PIHOLE_IP}"

  cloudflared:
    container_name: cloudflared-doh
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: proxy-dns
    ports:
      - "${CLOUDFLARED_PORT}:${CLOUDFLARED_PORT}"
    environment:
      TUNNEL_DNS_UPSTREAM: "https://1.0.0.1/dns-query,https://1.1.1.1/dns-query"
      TUNNEL_DNS_PORT: ${CLOUDFLARED_PORT}
      TUNNEL_DNS_ADDRESS: "0.0.0.0"
    networks:
      pihole:
        ipv4_address: "${CLOUDFLARED_IP}"

networks:
  pihole:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: "${PIHOLE_SUBNET}"