apiVersion: identity.oci.upbound.io/v1alpha1
kind: DynamicGroup
metadata:
  name: oracle-arm-instances
  namespace: monitoring
  labels:
    testing.upbound.io/example-name: oracle-arm-instances
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  forProvider:
    compartmentId: "ocid1.tenancy.oc1..aaaaaaaaic5nx2ifziikvx56su334ruzxqlmujowvwpfy7jodzvomlskbf2q"
    description: "Dynamic group for oracle-arm instance to allow metrics scraping"
    matchingRule: "Any {instance.id = 'ocid1.instance.oc1.eu-milan-1.anwgsljrbq3tbnacdncwoa2jnjjfrrhgxnr3gndmewbqmyn7bfzsqqwatqsa'}"
    name: "oracle-arm-instances"
  providerConfigRef:
    name: default
---
apiVersion: identity.oci.upbound.io/v1beta1
kind: Policy
metadata:
  name: oracle-arm-metrics-policy
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  forProvider:
    compartmentId: "ocid1.tenancy.oc1..aaaaaaaaic5nx2ifziikvx56su334ruzxqlmujowvwpfy7jodzvomlskbf2q"
    description: "Allow oracle-arm instances to push metrics to OCI Monitoring"
    name: "oracle-arm-metrics-policy"
    statements:
      - "Allow dynamic-group oracle-arm-instances to use metrics in tenancy"
  providerConfigRef:
    name: default
