apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-sologemma
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/belgio99/homelab.git
    targetRevision: main
    path: oracle-arm/wordpress-sologemma
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress-sologemma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
